

version: '3'

services:
  server:
    container_name: deploy_cesar
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/srv
      - ./nginx.conf:/etc/nginx/conf.d/default.conf